# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ChromeShare' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChromeShare
  pod 'MASShortcut'

  target 'ChromeShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChromeShareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
